import { Request, Vendor, Contract, PurchaseOrder, EnhancedRequest, EnhancedVendor, EnhancedContract, EnhancedPurchaseOrder, RFQ, Approval, ActionQueueItem, ActivityFeedItem, EnhancedApproval, IndentApproval, QuoteApproval, POApproval } from '@/types';

// Base mock data for automotive industry
export const mockRequests: Request[] = [
  {
    id: 'REQ-001',
    itemName: 'Engine Bearings - SKF 6205-2RS',
    quantity: 5000,
    estimatedCost: 875000,
    businessJustification: 'Critical component for Q1 engine assembly line. Production cannot continue without these bearings.',
    urgency: 'critical',
    status: 'pending',
    budgetStatus: 'under-budget',
    source: 'sap',
    requester: 'Rajesh Kumar',
    department: 'Powertrain Assembly',
    assignedProcurementManager: 'Priya Sharma',
    expectedTimeline: '5 days',
    createdAt: '2024-01-20T08:00:00Z',
    updatedAt: '2024-01-20T08:00:00Z',
  },
  {
    id: 'REQ-002',
    itemName: 'Automotive Grade Steel Coils - 1.2mm',
    quantity: 120,
    estimatedCost: 1450000,
    businessJustification: 'Quarterly body panel production requirement. JIT inventory replenishment for chassis line.',
    urgency: 'high',
    status: 'approved',
    budgetStatus: 'over-budget',
    source: 'sap',
    requester: 'Amit Patel',
    department: 'Body Shop',
    assignedProcurementManager: 'Vikram Singh',
    expectedTimeline: '10 days',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-18T14:30:00Z',
  },
  {
    id: 'REQ-003',
    itemName: 'ECU Sensors - Bosch Oxygen Sensors',
    quantity: 2500,
    estimatedCost: 625000,
    businessJustification: 'Electronic control unit sensors for new model launch. Quality upgrade requirement.',
    urgency: 'high',
    status: 'vendor-sourcing',
    budgetStatus: 'pending-allocation',
    source: 'form',
    requester: 'Deepak Verma',
    department: 'Electronics & Controls',
    expectedTimeline: '7 days',
    createdAt: '2024-01-17T09:00:00Z',
    updatedAt: '2024-01-19T11:00:00Z',
  },
];

export const mockVendors: Vendor[] = [
  {
    id: 'VND-001',
    name: 'SKF Automotive Bearings',
    category: 'hardware',
    status: 'active',
    activeContracts: 4,
    performanceRating: 4.9,
    totalSpend: 18500000, // Large bubble - high performer
  },
  {
    id: 'VND-002',
    name: 'ArcelorMittal Automotive Steel',
    category: 'materials',
    status: 'active',
    activeContracts: 2,
    performanceRating: 4.7,
    totalSpend: 22000000, // Very large bubble - high spend
  },
  {
    id: 'VND-003',
    name: 'Bosch Automotive Solutions',
    category: 'hardware',
    status: 'active',
    activeContracts: 3,
    performanceRating: 4.8,
    totalSpend: 12500000, // Medium-large bubble
  },
];

export const mockContracts: Contract[] = [
  {
    id: 'CNT-001',
    name: 'SKF Bearings Annual Supply Contract 2024',
    vendor: 'SKF Automotive Bearings',
    vendorId: 'VND-001',
    value: 8500000,
    status: 'executed',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
  },
  {
    id: 'CNT-002',
    name: 'ArcelorMittal Steel Supply Agreement Q1-Q4',
    vendor: 'ArcelorMittal Automotive Steel',
    vendorId: 'VND-002',
    value: 15000000,
    status: 'executed',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
  },
];

export const mockPurchaseOrders: PurchaseOrder[] = [
  {
    id: 'PO-001',
    poNumber: 'PO-2024-001',
    vendor: 'SKF Automotive Bearings',
    vendorId: 'VND-001',
    amount: 875000,
    status: 'approved',
    createdAt: '2024-01-20T08:00:00Z',
    assignedTo: 'Priya Sharma',
  },
  {
    id: 'PO-002',
    poNumber: 'PO-2024-002',
    vendor: 'ArcelorMittal Automotive Steel',
    vendorId: 'VND-002',
    amount: 1450000,
    status: 'pending',
    createdAt: '2024-01-15T10:00:00Z',
    assignedTo: 'Vikram Singh',
  },
];

export const monthlySpendData = [
  { month: 'Oct 2023', spend: 18500000 },
  { month: 'Nov 2023', spend: 19800000 },
  { month: 'Dec 2023', spend: 17200000 },
  { month: 'Jan 2024', spend: 22400000 },
  { month: 'Feb 2024', spend: 21800000 },
  { month: 'Mar 2024', spend: 23500000 },
];

export const categorySpendData = [
  { category: 'Steel & Raw Materials', spend: 48000000, percentage: 38 },
  { category: 'Engine Components', spend: 32000000, percentage: 25 },
  { category: 'Electronics & Sensors', spend: 22000000, percentage: 17 },
  { category: 'Tires & Wheels', spend: 15000000, percentage: 12 },
  { category: 'Paint & Coatings', spend: 8500000, percentage: 7 },
];

export const topVendorsData = [
  { name: 'ArcelorMittal Automotive Steel', spend: 15200000 },
  { name: 'SKF Automotive Bearings', spend: 8200000 },
  { name: 'Bosch Automotive Solutions', spend: 6800000 },
  { name: 'Michelin Tire Manufacturing', spend: 5400000 },
  { name: 'Continental Automotive', spend: 5200000 },
];

// Enhanced mock data - Automotive Industry
export const enhancedRequests: EnhancedRequest[] = [
  {
    ...mockRequests[0],
    validationStatus: 'pending',
    indentAge: 3,
    requiredDate: '2024-01-25',
  },
  {
    ...mockRequests[1],
    validationStatus: 'validated',
    indentAge: 8,
    requiredDate: '2024-01-25',
  },
  {
    ...mockRequests[2],
    validationStatus: 'validated',
    indentAge: 6,
    requiredDate: '2024-01-24',
  },
  {
    id: 'REQ-004',
    itemName: 'Brake Pads - Ceramic Composite',
    quantity: 8000,
    estimatedCost: 640000,
    businessJustification: 'High-performance brake pads for premium model. Safety upgrade for upcoming launch.',
    urgency: 'high',
    status: 'pending',
    budgetStatus: 'under-budget',
    source: 'form',
    requester: 'Suresh Reddy',
    department: 'Brake Systems',
    expectedTimeline: '6 days',
    createdAt: '2024-01-19T11:00:00Z',
    updatedAt: '2024-01-19T11:00:00Z',
    validationStatus: 'pending',
    indentAge: 4,
    requiredDate: '2024-01-25',
  },
  {
    id: 'REQ-005',
    itemName: 'Automotive Paint - Base Coat White',
    quantity: 2500,
    estimatedCost: 425000,
    businessJustification: 'Paint shop inventory for next month production. Color variant requirement.',
    urgency: 'medium',
    status: 'pending',
    budgetStatus: 'under-budget',
    source: 'sap',
    requester: 'Meera Joshi',
    department: 'Paint Shop',
    expectedTimeline: '8 days',
    createdAt: '2024-01-18T14:00:00Z',
    updatedAt: '2024-01-18T14:00:00Z',
    validationStatus: 'pending',
    indentAge: 5,
    requiredDate: '2024-02-05',
  },
  {
    id: 'REQ-006',
    itemName: 'Transmission Gears - Hardened Steel',
    quantity: 1500,
    estimatedCost: 1125000,
    businessJustification: 'Transmission assembly line requirement. Production cannot continue without gears.',
    urgency: 'critical',
    status: 'vendor-sourcing',
    budgetStatus: 'over-budget',
    source: 'sap',
    requester: 'Anil Kapoor',
    department: 'Transmission Assembly',
    expectedTimeline: '5 days',
    createdAt: '2024-01-16T08:00:00Z',
    updatedAt: '2024-01-21T16:00:00Z',
    validationStatus: 'validated',
    indentAge: 7,
    requiredDate: '2024-01-23',
  },
  {
    id: 'REQ-007',
    itemName: 'Wiring Harnesses - Engine Bay',
    quantity: 3500,
    estimatedCost: 875000,
    businessJustification: 'Complete wiring harness set for engine compartment. Model year update requirement.',
    urgency: 'high',
    status: 'pending',
    budgetStatus: 'under-budget',
    source: 'form',
    requester: 'Kiran Desai',
    department: 'Electrical Systems',
    expectedTimeline: '7 days',
    createdAt: '2024-01-21T09:00:00Z',
    updatedAt: '2024-01-21T09:00:00Z',
    validationStatus: 'pending',
    indentAge: 2,
    requiredDate: '2024-01-28',
  },
  {
    id: 'REQ-008',
    itemName: 'Lithium-Ion Battery Cells - 18650',
    quantity: 15000,
    estimatedCost: 2850000,
    businessJustification: 'Battery pack assembly for hybrid models. Critical for EV production line.',
    urgency: 'critical',
    status: 'approved',
    budgetStatus: 'pending-allocation',
    source: 'sap',
    requester: 'Ravi Nair',
    department: 'Battery Assembly',
    expectedTimeline: '10 days',
    createdAt: '2024-01-12T10:00:00Z',
    updatedAt: '2024-01-19T15:30:00Z',
    validationStatus: 'validated',
    indentAge: 11,
    requiredDate: '2024-01-30',
  },
  {
    id: 'REQ-009',
    itemName: 'Windshield Glass - Laminated',
    quantity: 1200,
    estimatedCost: 420000,
    businessJustification: 'Front and rear windshield glass for new model. Safety standard compliance.',
    urgency: 'medium',
    status: 'pending',
    budgetStatus: 'under-budget',
    source: 'form',
    requester: 'Pooja Mehta',
    department: 'Body Assembly',
    expectedTimeline: '9 days',
    createdAt: '2024-01-20T13:00:00Z',
    updatedAt: '2024-01-20T13:00:00Z',
    validationStatus: 'pending',
    indentAge: 3,
    requiredDate: '2024-02-05',
  },
  {
    id: 'REQ-010',
    itemName: 'Suspension Coil Springs - Front',
    quantity: 2400,
    estimatedCost: 480000,
    businessJustification: 'Suspension system components for chassis assembly. Maintenance of production cadence.',
    urgency: 'critical',
    status: 'vendor-sourcing',
    budgetStatus: 'over-budget',
    source: 'sap',
    requester: 'Manoj Agarwal',
    department: 'Chassis Assembly',
    expectedTimeline: '4 days',
    createdAt: '2024-01-19T07:00:00Z',
    updatedAt: '2024-01-22T12:00:00Z',
    validationStatus: 'validated',
    indentAge: 4,
    requiredDate: '2024-01-25',
  },
  // Duplicate items for Repeating Items widget
  {
    id: 'REQ-011',
    itemName: 'Engine Bearings - SKF 6205-2RS',
    quantity: 3000,
    estimatedCost: 525000,
    businessJustification: 'Additional bearings requirement for production ramp-up. Spare parts inventory.',
    urgency: 'high',
    status: 'pending',
    budgetStatus: 'under-budget',
    source: 'form',
    requester: 'Vikram Mehta',
    department: 'Quality Assurance',
    expectedTimeline: '6 days',
    createdAt: '2024-01-21T10:00:00Z',
    updatedAt: '2024-01-21T10:00:00Z',
    validationStatus: 'pending',
    indentAge: 2,
    requiredDate: '2024-01-30',
  },
  {
    id: 'REQ-012',
    itemName: 'Engine Bearings - SKF 6205-2RS',
    quantity: 2000,
    estimatedCost: 350000,
    businessJustification: 'Maintenance spare parts for service center operations.',
    urgency: 'medium',
    status: 'pending',
    budgetStatus: 'under-budget',
    source: 'sap',
    requester: 'Arjun Singh',
    department: 'Service Center',
    expectedTimeline: '8 days',
    createdAt: '2024-01-22T09:00:00Z',
    updatedAt: '2024-01-22T09:00:00Z',
    validationStatus: 'pending',
    indentAge: 1,
    requiredDate: '2024-02-05',
  },
  {
    id: 'REQ-013',
    itemName: 'Brake Pads - Ceramic Composite',
    quantity: 5000,
    estimatedCost: 400000,
    businessJustification: 'Aftermarket brake pads for service replacement. Customer demand surge.',
    urgency: 'high',
    status: 'pending',
    budgetStatus: 'under-budget',
    source: 'form',
    requester: 'Ramesh Iyer',
    department: 'Aftermarket Sales',
    expectedTimeline: '7 days',
    createdAt: '2024-01-20T14:00:00Z',
    updatedAt: '2024-01-20T14:00:00Z',
    validationStatus: 'validated',
    indentAge: 3,
    requiredDate: '2024-02-01',
  },
  {
    id: 'REQ-014',
    itemName: 'Automotive Grade Steel Coils - 1.2mm',
    quantity: 90,
    estimatedCost: 1087500,
    businessJustification: 'Additional steel requirement for body panel modification. Design change implementation.',
    urgency: 'high',
    status: 'pending',
    budgetStatus: 'over-budget',
    source: 'sap',
    requester: 'Lokesh Reddy',
    department: 'Body Design',
    expectedTimeline: '9 days',
    createdAt: '2024-01-18T11:00:00Z',
    updatedAt: '2024-01-18T11:00:00Z',
    validationStatus: 'pending',
    indentAge: 5,
    requiredDate: '2024-01-30',
  },
  {
    id: 'REQ-015',
    itemName: 'Automotive Grade Steel Coils - 1.2mm',
    quantity: 100,
    estimatedCost: 1200000,
    businessJustification: 'Prototype development requirement. R&D project material.',
    urgency: 'medium',
    status: 'pending',
    budgetStatus: 'pending-allocation',
    source: 'form',
    requester: 'Karthik Nair',
    department: 'R&D Center',
    expectedTimeline: '10 days',
    createdAt: '2024-01-17T15:00:00Z',
    updatedAt: '2024-01-17T15:00:00Z',
    validationStatus: 'pending',
    indentAge: 6,
    requiredDate: '2024-02-10',
  },
  {
    id: 'REQ-016',
    itemName: 'Wiring Harnesses - Engine Bay',
    quantity: 2500,
    estimatedCost: 625000,
    businessJustification: 'Additional wiring for optional equipment installation. Premium variant requirement.',
    urgency: 'medium',
    status: 'pending',
    budgetStatus: 'under-budget',
    source: 'sap',
    requester: 'Sandeep Kumar',
    department: 'Premium Variants',
    expectedTimeline: '8 days',
    createdAt: '2024-01-22T08:00:00Z',
    updatedAt: '2024-01-22T08:00:00Z',
    validationStatus: 'pending',
    indentAge: 1,
    requiredDate: '2024-02-05',
  },
];

export const enhancedVendors: EnhancedVendor[] = [
  {
    ...mockVendors[0],
    onTimeDeliveryPercent: 98, // High on-time, High quality (top-right)
    qualityPercent: 99,
    avgLeadTimeDays: 5,
    healthStatus: 'green',
    healthScore: 94,
  },
  {
    ...mockVendors[1],
    onTimeDeliveryPercent: 96, // High on-time, High quality (top-right)
    qualityPercent: 98,
    avgLeadTimeDays: 8,
    healthStatus: 'green',
    healthScore: 91,
  },
  {
    ...mockVendors[2],
    onTimeDeliveryPercent: 95, // High on-time, Low quality (bottom-right)
    qualityPercent: 68,
    avgLeadTimeDays: 6,
    healthStatus: 'amber',
    healthScore: 72,
  },
  {
    id: 'VND-004',
    name: 'Michelin Tire Manufacturing',
    category: 'hardware',
    status: 'active',
    activeContracts: 2,
    performanceRating: 4.6,
    totalSpend: 8500000, // Medium bubble
    onTimeDeliveryPercent: 72, // Low on-time, High quality (top-left)
    qualityPercent: 94,
    avgLeadTimeDays: 12,
    healthStatus: 'amber',
    healthScore: 75,
  },
  {
    id: 'VND-005',
    name: 'Continental Automotive',
    category: 'hardware',
    status: 'active',
    activeContracts: 3,
    performanceRating: 4.7,
    totalSpend: 12000000, // Medium-large bubble
    onTimeDeliveryPercent: 89, // Medium-high on-time, Medium-high quality
    qualityPercent: 86,
    avgLeadTimeDays: 9,
    healthStatus: 'green',
    healthScore: 83,
  },
  {
    id: 'VND-006',
    name: 'Tata Steel Automotive',
    category: 'materials',
    status: 'active',
    activeContracts: 1,
    performanceRating: 4.4,
    totalSpend: 2800000, // Small bubble
    onTimeDeliveryPercent: 25, // Very low on-time (At-Risk)
    qualityPercent: 35, // Very low quality (At-Risk)
    avgLeadTimeDays: 15,
    healthStatus: 'amber',
    healthScore: 58,
  },
  {
    id: 'VND-007',
    name: 'PPG Automotive Coatings',
    category: 'materials',
    status: 'active',
    activeContracts: 2,
    performanceRating: 4.5,
    totalSpend: 1500000, // Very small bubble
    onTimeDeliveryPercent: 25, // Very low on-time (At-Risk)
    qualityPercent: 30, // Very low quality (At-Risk)
    avgLeadTimeDays: 11,
    healthStatus: 'amber',
    healthScore: 62,
  },
  {
    id: 'VND-008',
    name: 'Denso Automotive Components',
    category: 'hardware',
    status: 'active',
    activeContracts: 2,
    performanceRating: 4.8,
    totalSpend: 6200000, // Medium bubble
    onTimeDeliveryPercent: 99, // Very high on-time, High quality (top-right)
    qualityPercent: 97,
    avgLeadTimeDays: 4,
    healthStatus: 'green',
    healthScore: 98,
  },
];

export const enhancedContracts: EnhancedContract[] = [
  {
    ...mockContracts[0],
    utilizedPercent: 72,
    daysToExpiry: 334,
  },
  {
    ...mockContracts[1],
    utilizedPercent: 68,
    daysToExpiry: 334,
  },
  {
    id: 'CNT-003',
    name: 'Bosch Electronics Supply Contract 2024',
    vendor: 'Bosch Automotive Solutions',
    vendorId: 'VND-003',
    value: 7200000,
    status: 'executed',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    utilizedPercent: 58,
    daysToExpiry: 334,
  },
  {
    id: 'CNT-004',
    name: 'Michelin Tire Supply Agreement Q1-Q4',
    vendor: 'Michelin Tire Manufacturing',
    vendorId: 'VND-004',
    value: 5800000,
    status: 'executed',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    utilizedPercent: 62,
    daysToExpiry: 334,
  },
  {
    id: 'CNT-005',
    name: 'PPG Paint Supply Contract 2024',
    vendor: 'PPG Automotive Coatings',
    vendorId: 'VND-007',
    value: 4000000,
    status: 'executed',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    utilizedPercent: 54,
    daysToExpiry: 334,
  },
  {
    id: 'CNT-006',
    name: 'Denso Components Supply Agreement',
    vendor: 'Denso Automotive Components',
    vendorId: 'VND-008',
    value: 4500000,
    status: 'executed',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    utilizedPercent: 47,
    daysToExpiry: 334,
  },
];

export const enhancedPurchaseOrders: EnhancedPurchaseOrder[] = [
  {
    ...mockPurchaseOrders[0],
    grnStatus: 'received',
    invoiceStatus: 'pending',
    age: 3,
    costCenter: 'CC-PWR-001',
    budgetCode: 'BUD-2024-Q1-PWR',
  },
  {
    ...mockPurchaseOrders[1],
    grnStatus: 'pending',
    invoiceStatus: 'pending',
    age: 8,
    costCenter: 'CC-BDY-001',
    budgetCode: 'BUD-2024-Q1-BDY',
  },
  {
    id: 'PO-003',
    poNumber: 'PO-2024-003',
    vendor: 'Bosch Automotive Solutions',
    vendorId: 'VND-003',
    amount: 625000,
    status: 'delivered',
    createdAt: '2024-01-17T09:00:00Z',
    assignedTo: 'Vikram Singh',
    grnStatus: 'received',
    invoiceStatus: 'received',
    age: 6,
    costCenter: 'CC-ELC-001',
    budgetCode: 'BUD-2024-Q1-ELC',
    dueDeliveryDate: '2024-01-23',
  },
  {
    id: 'PO-004',
    poNumber: 'PO-2024-004',
    vendor: 'Michelin Tire Manufacturing',
    vendorId: 'VND-004',
    amount: 640000,
    status: 'approved',
    createdAt: '2024-01-19T11:00:00Z',
    assignedTo: 'Priya Sharma',
    grnStatus: 'pending',
    invoiceStatus: 'pending',
    age: 4,
    costCenter: 'CC-BRK-001',
    budgetCode: 'BUD-2024-Q1-BRK',
    dueDeliveryDate: '2024-01-25',
  },
  {
    id: 'PO-005',
    poNumber: 'PO-2024-005',
    vendor: 'PPG Automotive Coatings',
    vendorId: 'VND-007',
    amount: 425000,
    status: 'pending',
    createdAt: '2024-01-18T14:00:00Z',
    assignedTo: 'Vikram Singh',
    grnStatus: 'pending',
    invoiceStatus: 'pending',
    age: 5,
    costCenter: 'CC-PNT-001',
    budgetCode: 'BUD-2024-Q1-PNT',
    dueDeliveryDate: '2024-02-05',
  },
  {
    id: 'PO-006',
    poNumber: 'PO-2024-006',
    vendor: 'Continental Automotive',
    vendorId: 'VND-005',
    amount: 480000,
    status: 'approved',
    createdAt: '2024-01-19T07:00:00Z',
    assignedTo: 'Priya Sharma',
    grnStatus: 'pending',
    invoiceStatus: 'pending',
    age: 4,
    costCenter: 'CC-CHS-001',
    budgetCode: 'BUD-2024-Q1-CHS',
    dueDeliveryDate: '2024-01-25',
  },
  {
    id: 'PO-007',
    poNumber: 'PO-2024-007',
    vendor: 'Denso Automotive Components',
    vendorId: 'VND-008',
    amount: 875000,
    status: 'delivered',
    createdAt: '2024-01-21T09:00:00Z',
    assignedTo: 'Vikram Singh',
    grnStatus: 'received',
    invoiceStatus: 'received',
    age: 2,
    costCenter: 'CC-ELC-002',
    budgetCode: 'BUD-2024-Q1-ELC',
    dueDeliveryDate: '2024-01-28',
  },
  {
    id: 'PO-008A',
    poNumber: 'PO-2024-008A',
    vendor: 'SKF Automotive Bearings',
    vendorId: 'VND-001',
    amount: 925000,
    status: 'delivered',
    createdAt: '2024-01-15T10:00:00Z',
    assignedTo: 'Priya Sharma',
    grnStatus: 'received',
    invoiceStatus: 'received',
    age: 8,
    costCenter: 'CC-PWR-002',
    budgetCode: 'BUD-2024-Q1-PWR',
    dueDeliveryDate: '2024-01-23',
  },
  {
    id: 'PO-009A',
    poNumber: 'PO-2024-009A',
    vendor: 'SKF Automotive Bearings',
    vendorId: 'VND-001',
    amount: 750000,
    status: 'delivered',
    createdAt: '2024-01-10T09:00:00Z',
    assignedTo: 'Priya Sharma',
    grnStatus: 'received',
    invoiceStatus: 'received',
    age: 13,
    costCenter: 'CC-PWR-003',
    budgetCode: 'BUD-2024-Q1-PWR',
    dueDeliveryDate: '2024-01-18',
  },
  {
    id: 'PO-010A',
    poNumber: 'PO-2024-010A',
    vendor: 'SKF Automotive Bearings',
    vendorId: 'VND-001',
    amount: 1100000,
    status: 'approved',
    createdAt: '2024-01-05T08:00:00Z',
    assignedTo: 'Priya Sharma',
    grnStatus: 'pending',
    invoiceStatus: 'pending',
    age: 18,
    costCenter: 'CC-PWR-004',
    budgetCode: 'BUD-2024-Q1-PWR',
    dueDeliveryDate: '2024-01-15',
  },
  {
    id: 'PO-011A',
    poNumber: 'PO-2024-011A',
    vendor: 'SKF Automotive Bearings',
    vendorId: 'VND-001',
    amount: 680000,
    status: 'delivered',
    createdAt: '2023-12-28T10:00:00Z',
    assignedTo: 'Priya Sharma',
    grnStatus: 'received',
    invoiceStatus: 'received',
    age: 25,
    costCenter: 'CC-PWR-005',
    budgetCode: 'BUD-2023-Q4-PWR',
    dueDeliveryDate: '2024-01-05',
  },
  {
    id: 'PO-012A',
    poNumber: 'PO-2024-012A',
    vendor: 'SKF Automotive Bearings',
    vendorId: 'VND-001',
    amount: 950000,
    status: 'delivered',
    createdAt: '2023-12-20T09:00:00Z',
    assignedTo: 'Priya Sharma',
    grnStatus: 'received',
    invoiceStatus: 'received',
    age: 33,
    costCenter: 'CC-PWR-006',
    budgetCode: 'BUD-2023-Q4-PWR',
    dueDeliveryDate: '2023-12-30',
  },
  {
    id: 'PO-008',
    poNumber: 'PO-2024-008',
    vendor: 'Tata Steel Automotive',
    vendorId: 'VND-006',
    amount: 1125000,
    status: 'approved',
    createdAt: '2024-01-16T08:00:00Z',
    assignedTo: 'Priya Sharma',
    grnStatus: 'received',
    invoiceStatus: 'received',
    age: 8,
    costCenter: 'CC-PWR-002',
    budgetCode: 'BUD-2024-Q1-PWR',
    dueDeliveryDate: '2024-01-23',
  },
  {
    id: 'PO-009',
    poNumber: 'PO-2024-009',
    vendor: 'SKF Automotive Bearings',
    vendorId: 'VND-001',
    amount: 750000,
    status: 'delivered',
    createdAt: '2024-01-10T09:00:00Z',
    assignedTo: 'Priya Sharma',
    grnStatus: 'received',
    invoiceStatus: 'received',
    age: 13,
    costCenter: 'CC-PWR-003',
    budgetCode: 'BUD-2024-Q1-PWR',
    dueDeliveryDate: '2024-01-18',
  },
  {
    id: 'PO-010',
    poNumber: 'PO-2024-010',
    vendor: 'SKF Automotive Bearings',
    vendorId: 'VND-001',
    amount: 1100000,
    status: 'approved',
    createdAt: '2024-01-05T08:00:00Z',
    assignedTo: 'Priya Sharma',
    grnStatus: 'pending',
    invoiceStatus: 'pending',
    age: 18,
    costCenter: 'CC-PWR-004',
    budgetCode: 'BUD-2024-Q1-PWR',
    dueDeliveryDate: '2024-01-15',
  },
  {
    id: 'PO-011',
    poNumber: 'PO-2024-011',
    vendor: 'SKF Automotive Bearings',
    vendorId: 'VND-001',
    amount: 680000,
    status: 'delivered',
    createdAt: '2023-12-28T10:00:00Z',
    assignedTo: 'Priya Sharma',
    grnStatus: 'received',
    invoiceStatus: 'received',
    age: 25,
    costCenter: 'CC-PWR-005',
    budgetCode: 'BUD-2023-Q4-PWR',
    dueDeliveryDate: '2024-01-05',
  },
  {
    id: 'PO-012',
    poNumber: 'PO-2024-012',
    vendor: 'SKF Automotive Bearings',
    vendorId: 'VND-001',
    amount: 950000,
    status: 'delivered',
    createdAt: '2023-12-20T09:00:00Z',
    assignedTo: 'Priya Sharma',
    grnStatus: 'received',
    invoiceStatus: 'received',
    age: 33,
    costCenter: 'CC-PWR-006',
    budgetCode: 'BUD-2023-Q4-PWR',
    dueDeliveryDate: '2023-12-30',
  },
  {
    id: 'PO-013',
    poNumber: 'PO-2024-013',
    vendor: 'Tata Steel Automotive',
    vendorId: 'VND-006',
    amount: 1125000,
    status: 'approved',
    createdAt: '2024-01-16T08:00:00Z',
    assignedTo: 'Priya Sharma',
    grnStatus: 'pending',
    invoiceStatus: 'pending',
    age: 7,
    costCenter: 'CC-TRN-001',
    budgetCode: 'BUD-2024-Q1-TRN',
    dueDeliveryDate: '2024-01-23',
  },
];

export const mockRFQs: RFQ[] = [
  {
    id: 'RFQ-001',
    rfqNumber: 'RFQ-2024-001',
    itemName: 'Engine Bearings - SKF 6205-2RS',
    category: 'Hardware',
    suppliersInvited: 5,
    suppliersResponded: 4,
    lowestQuote: 850000,
    dueDate: '2024-01-25T23:59:59Z',
    status: 'quotes-received',
    quoteVariance: 12,
  },
  {
    id: 'RFQ-002',
    rfqNumber: 'RFQ-2024-002',
    itemName: 'Automotive Grade Steel Coils',
    category: 'Materials',
    suppliersInvited: 4,
    suppliersResponded: 3,
    lowestQuote: 1420000,
    dueDate: '2024-01-28T23:59:59Z',
    status: 'sent',
    quoteVariance: 8,
  },
  {
    id: 'RFQ-003',
    rfqNumber: 'RFQ-2024-003',
    itemName: 'Transmission Gears - Hardened Steel',
    category: 'Hardware',
    suppliersInvited: 6,
    suppliersResponded: 5,
    lowestQuote: 1100000,
    dueDate: '2024-01-23T23:59:59Z',
    status: 'quotes-received',
    quoteVariance: 15,
  },
  {
    id: 'RFQ-004',
    rfqNumber: 'RFQ-2024-004',
    itemName: 'Brake Pads - Ceramic Composite',
    category: 'Hardware',
    suppliersInvited: 4,
    suppliersResponded: 3,
    lowestQuote: 625000,
    dueDate: '2024-01-26T23:59:59Z',
    status: 'sent',
    quoteVariance: 18,
  },
  {
    id: 'RFQ-005',
    rfqNumber: 'RFQ-2024-005',
    itemName: 'Lithium-Ion Battery Cells - 18650',
    category: 'Hardware',
    suppliersInvited: 3,
    suppliersResponded: 2,
    lowestQuote: 2800000,
    dueDate: '2024-02-01T23:59:59Z',
    status: 'sent',
    quoteVariance: 22,
  },
  {
    id: 'RFQ-006',
    rfqNumber: 'RFQ-2024-006',
    itemName: 'Suspension Coil Springs - Front',
    category: 'Hardware',
    suppliersInvited: 5,
    suppliersResponded: 4,
    lowestQuote: 465000,
    dueDate: '2024-01-25T23:59:59Z',
    status: 'quotes-received',
    quoteVariance: 11,
  },
];

// Legacy approvals (for backward compatibility)
export const mockApprovals: Approval[] = [
  {
    id: 'APR-001',
    type: 'Purchase Order',
    referenceNumber: 'PO-2024-002',
    value: 1450000,
    status: 'pending',
    age: 8,
    approverLevel: 2,
    slaTarget: 48,
    slaActual: 36,
  },
  {
    id: 'APR-002',
    referenceNumber: 'PO-2024-004',
    type: 'Purchase Order',
    value: 640000,
    status: 'pending',
    age: 4,
    approverLevel: 1,
    slaTarget: 24,
  },
  {
    id: 'APR-003',
    type: 'Purchase Order',
    referenceNumber: 'PO-2024-005',
    value: 425000,
    status: 'pending',
    age: 5,
    approverLevel: 1,
    slaTarget: 24,
  },
  {
    id: 'APR-004',
    type: 'Purchase Order',
    referenceNumber: 'PO-2024-008',
    value: 1125000,
    status: 'pending',
    age: 7,
    approverLevel: 2,
    slaTarget: 48,
  },
  {
    id: 'APR-005',
    type: 'Contract',
    referenceNumber: 'CNT-006',
    value: 4500000,
    status: 'pending',
    age: 2,
    approverLevel: 3,
    slaTarget: 72,
  },
];

// Enhanced approvals hub data
export const enhancedApprovals: EnhancedApproval[] = [
  // INDENT APPROVALS
  {
    id: 'APR-IND-001',
    approvalType: 'INDENT',
    referenceId: 'REQ-010',
    referenceNumber: 'REQ-010',
    title: 'Suspension Coil Springs - Front & Rear',
    value: 980000,
    approverLevel: 'L1',
    submittedAt: '2024-01-21T10:30:00Z',
    slaTargetHours: 24,
    slaElapsedHours: 18,
    status: 'pending',
    requester: 'Vikram Mehta',
    dept: 'Chassis Assembly',
    itemName: 'Suspension Coil Springs - Front & Rear',
    quantity: 2000,
    estimatedCost: 980000,
    budgetHead: 'Chassis Components',
    budgetStatus: 'under-budget',
    urgency: 'critical',
    blockerReason: undefined,
    attachments: [
      { name: 'Technical_Spec_Coil_Springs.pdf', type: 'pdf' },
      { name: 'Drawings_Rev_2.1.dwg', type: 'dwg' },
    ],
  },
  {
    id: 'APR-IND-002',
    approvalType: 'INDENT',
    referenceId: 'REQ-011',
    referenceNumber: 'REQ-011',
    title: 'Transmission Gears - Helical Type',
    value: 1125000,
    approverLevel: 'L2',
    submittedAt: '2024-01-20T14:15:00Z',
    slaTargetHours: 48,
    slaElapsedHours: 42,
    status: 'pending',
    requester: 'Anjali Desai',
    dept: 'Powertrain Assembly',
    itemName: 'Transmission Gears - Helical Type',
    quantity: 800,
    estimatedCost: 1125000,
    budgetHead: 'Transmission Systems',
    budgetStatus: 'over-budget',
    urgency: 'high',
    blockerReason: 'budget',
  },
  {
    id: 'APR-IND-003',
    approvalType: 'INDENT',
    referenceId: 'REQ-012',
    referenceNumber: 'REQ-012',
    title: 'Brake Pads - Ceramic Composite',
    value: 675000,
    approverLevel: 'L1',
    submittedAt: '2024-01-22T09:00:00Z',
    slaTargetHours: 24,
    slaElapsedHours: 5,
    status: 'pending',
    requester: 'Rajesh Kumar',
    dept: 'Brake Systems',
    itemName: 'Brake Pads - Ceramic Composite',
    quantity: 3500,
    estimatedCost: 675000,
    budgetHead: 'Brake Components',
    budgetStatus: 'under-budget',
    urgency: 'high',
  },
  {
    id: 'APR-IND-004',
    approvalType: 'INDENT',
    referenceId: 'REQ-013',
    referenceNumber: 'REQ-013',
    title: 'Battery Cells - Lithium Ion 18650',
    value: 2450000,
    approverLevel: 'Head',
    submittedAt: '2024-01-19T11:20:00Z',
    slaTargetHours: 72,
    slaElapsedHours: 68,
    status: 'pending',
    requester: 'Pradeep Nair',
    dept: 'Electronics & Controls',
    itemName: 'Battery Cells - Lithium Ion 18650',
    quantity: 10000,
    estimatedCost: 2450000,
    budgetHead: 'Battery Systems',
    budgetStatus: 'pending-allocation',
    urgency: 'high',
    blockerReason: 'budget',
  },
  {
    id: 'APR-IND-005',
    approvalType: 'INDENT',
    referenceId: 'REQ-014',
    referenceNumber: 'REQ-014',
    title: 'Wiring Harnesses - Engine Bay',
    value: 485000,
    approverLevel: 'L1',
    submittedAt: '2024-01-22T08:30:00Z',
    slaTargetHours: 24,
    slaElapsedHours: 3,
    status: 'pending',
    requester: 'Suresh Reddy',
    dept: 'Electronics & Controls',
    itemName: 'Wiring Harnesses - Engine Bay',
    quantity: 1500,
    estimatedCost: 485000,
    budgetHead: 'Wiring Systems',
    budgetStatus: 'under-budget',
    urgency: 'medium',
  },
  {
    id: 'APR-IND-006',
    approvalType: 'INDENT',
    referenceId: 'REQ-015',
    referenceNumber: 'REQ-015',
    title: 'Exhaust Manifolds - Cast Iron',
    value: 1250000,
    approverLevel: 'L2',
    submittedAt: '2024-01-20T08:45:00Z',
    slaTargetHours: 48,
    slaElapsedHours: 44,
    status: 'pending',
    requester: 'Amit Patel',
    dept: 'Powertrain Assembly',
    itemName: 'Exhaust Manifolds - Cast Iron',
    quantity: 600,
    estimatedCost: 1250000,
    budgetHead: 'Exhaust Systems',
    budgetStatus: 'under-budget',
    urgency: 'high',
  },
  {
    id: 'APR-IND-007',
    approvalType: 'INDENT',
    referenceId: 'REQ-016',
    referenceNumber: 'REQ-016',
    title: 'Fuel Injectors - High Pressure',
    value: 1850000,
    approverLevel: 'L2',
    submittedAt: '2024-01-19T16:20:00Z',
    slaTargetHours: 48,
    slaElapsedHours: 54,
    status: 'pending',
    requester: 'Anjali Desai',
    dept: 'Powertrain Assembly',
    itemName: 'Fuel Injectors - High Pressure',
    quantity: 1200,
    estimatedCost: 1850000,
    budgetHead: 'Fuel Systems',
    budgetStatus: 'over-budget',
    urgency: 'critical',
    blockerReason: 'budget',
  },
  {
    id: 'APR-IND-008',
    approvalType: 'INDENT',
    referenceId: 'REQ-017',
    referenceNumber: 'REQ-017',
    title: 'Radiator Fans - Electric Dual Speed',
    value: 425000,
    approverLevel: 'L1',
    submittedAt: '2024-01-22T07:15:00Z',
    slaTargetHours: 24,
    slaElapsedHours: 7,
    status: 'pending',
    requester: 'Deepak Verma',
    dept: 'Powertrain Assembly',
    itemName: 'Automotive Radiator Fans - Electric Dual Speed Cooling',
    quantity: 800,
    estimatedCost: 425000,
    budgetHead: 'Cooling Systems',
    budgetStatus: 'under-budget',
    urgency: 'medium',
  },
  {
    id: 'APR-IND-009',
    approvalType: 'INDENT',
    referenceId: 'REQ-018',
    referenceNumber: 'REQ-018',
    title: 'Dashboard Instrument Cluster',
    value: 1650000,
    approverLevel: 'Head',
    submittedAt: '2024-01-18T13:30:00Z',
    slaTargetHours: 72,
    slaElapsedHours: 92,
    status: 'pending',
    requester: 'Priya Sharma',
    dept: 'Electronics & Controls',
    itemName: 'Dashboard Instrument Cluster',
    quantity: 500,
    estimatedCost: 1650000,
    budgetHead: 'Electronics',
    budgetStatus: 'over-budget',
    urgency: 'high',
    blockerReason: 'budget',
  },
  {
    id: 'APR-IND-010',
    approvalType: 'INDENT',
    referenceId: 'REQ-019',
    referenceNumber: 'REQ-019',
    title: 'Crankshaft Bearings - Main & Conrod',
    value: 895000,
    approverLevel: 'L1',
    submittedAt: '2024-01-21T11:45:00Z',
    slaTargetHours: 24,
    slaElapsedHours: 17,
    status: 'pending',
    requester: 'Vikram Mehta',
    dept: 'Powertrain Assembly',
    itemName: 'Crankshaft Bearings - Main & Conrod',
    quantity: 2400,
    estimatedCost: 895000,
    budgetHead: 'Engine Components',
    budgetStatus: 'under-budget',
    urgency: 'critical',
  },
  {
    id: 'APR-IND-011',
    approvalType: 'INDENT',
    referenceId: 'REQ-020',
    referenceNumber: 'REQ-020',
    title: 'Cylinder Head Gaskets - Multi-Layer',
    value: 385000,
    approverLevel: 'L1',
    submittedAt: '2024-01-22T06:30:00Z',
    slaTargetHours: 24,
    slaElapsedHours: 8,
    status: 'pending',
    requester: 'Rajesh Kumar',
    dept: 'Powertrain Assembly',
    itemName: 'Cylinder Head Gaskets - Multi-Layer',
    quantity: 1500,
    estimatedCost: 385000,
    budgetHead: 'Engine Components',
    budgetStatus: 'under-budget',
    urgency: 'high',
  },
  {
    id: 'APR-IND-012',
    approvalType: 'INDENT',
    referenceId: 'REQ-021',
    referenceNumber: 'REQ-021',
    title: 'Seat Belts - 3-Point Retractable',
    value: 725000,
    approverLevel: 'L1',
    submittedAt: '2024-01-21T15:20:00Z',
    slaTargetHours: 24,
    slaElapsedHours: 13,
    status: 'pending',
    requester: 'Suresh Reddy',
    dept: 'Body Shop',
    itemName: 'Seat Belts - 3-Point Retractable',
    quantity: 2800,
    estimatedCost: 725000,
    budgetHead: 'Safety Components',
    budgetStatus: 'under-budget',
    urgency: 'medium',
  },
  {
    id: 'APR-IND-013',
    approvalType: 'INDENT',
    referenceId: 'REQ-022',
    referenceNumber: 'REQ-022',
    title: 'ABS Sensors - Wheel Speed',
    value: 545000,
    approverLevel: 'L1',
    submittedAt: '2024-01-22T05:45:00Z',
    slaTargetHours: 24,
    slaElapsedHours: 9,
    status: 'pending',
    requester: 'Deepak Verma',
    dept: 'Brake Systems',
    itemName: 'ABS Sensors - Wheel Speed',
    quantity: 1600,
    estimatedCost: 545000,
    budgetHead: 'Brake Components',
    budgetStatus: 'under-budget',
    urgency: 'high',
  },
  {
    id: 'APR-IND-014',
    approvalType: 'INDENT',
    referenceId: 'REQ-023',
    referenceNumber: 'REQ-023',
    title: 'Turbocharger Compressors',
    value: 3250000,
    approverLevel: 'CFO',
    submittedAt: '2024-01-17T10:00:00Z',
    slaTargetHours: 96,
    slaElapsedHours: 118,
    status: 'pending',
    requester: 'Anjali Desai',
    dept: 'Powertrain Assembly',
    itemName: 'Turbocharger Compressors',
    quantity: 400,
    estimatedCost: 3250000,
    budgetHead: 'Forced Induction',
    budgetStatus: 'pending-allocation',
    urgency: 'high',
    blockerReason: 'budget',
  },
  {
    id: 'APR-IND-015',
    approvalType: 'INDENT',
    referenceId: 'REQ-024',
    referenceNumber: 'REQ-024',
    title: 'Headlights - LED Adaptive',
    value: 2150000,
    approverLevel: 'Head',
    submittedAt: '2024-01-19T09:30:00Z',
    slaTargetHours: 72,
    slaElapsedHours: 71,
    status: 'pending',
    requester: 'Priya Sharma',
    dept: 'Body Shop',
    itemName: 'Headlights - LED Adaptive',
    quantity: 1000,
    estimatedCost: 2150000,
    budgetHead: 'Lighting Systems',
    budgetStatus: 'over-budget',
    urgency: 'high',
    blockerReason: 'budget',
  },
  {
    id: 'APR-IND-016',
    approvalType: 'INDENT',
    referenceId: 'REQ-025',
    referenceNumber: 'REQ-025',
    title: 'Oil Filters - High Efficiency',
    value: 285000,
    approverLevel: 'L1',
    submittedAt: '2024-01-22T04:20:00Z',
    slaTargetHours: 24,
    slaElapsedHours: 10,
    status: 'pending',
    requester: 'Rajesh Kumar',
    dept: 'Powertrain Assembly',
    itemName: 'Oil Filters - High Efficiency',
    quantity: 5000,
    estimatedCost: 285000,
    budgetHead: 'Lubrication Systems',
    budgetStatus: 'under-budget',
    urgency: 'low',
  },
  {
    id: 'APR-IND-017',
    approvalType: 'INDENT',
    referenceId: 'REQ-026',
    referenceNumber: 'REQ-026',
    title: 'Catalytic Converters - Three-Way',
    value: 1850000,
    approverLevel: 'L2',
    submittedAt: '2024-01-20T12:00:00Z',
    slaTargetHours: 48,
    slaElapsedHours: 41,
    status: 'pending',
    requester: 'Amit Patel',
    dept: 'Powertrain Assembly',
    itemName: 'Catalytic Converters - Three-Way',
    quantity: 700,
    estimatedCost: 1850000,
    budgetHead: 'Emission Control',
    budgetStatus: 'under-budget',
    urgency: 'high',
  },
  {
    id: 'APR-IND-018',
    approvalType: 'INDENT',
    referenceId: 'REQ-027',
    referenceNumber: 'REQ-027',
    title: 'Power Steering Hoses - High Pressure',
    value: 365000,
    approverLevel: 'L1',
    submittedAt: '2024-01-22T03:15:00Z',
    slaTargetHours: 24,
    slaElapsedHours: 11,
    status: 'pending',
    requester: 'Vikram Mehta',
    dept: 'Chassis Assembly',
    itemName: 'Power Steering Hoses - High Pressure',
    quantity: 1200,
    estimatedCost: 365000,
    budgetHead: 'Steering Systems',
    budgetStatus: 'under-budget',
    urgency: 'medium',
  },
  {
    id: 'APR-IND-019',
    approvalType: 'INDENT',
    referenceId: 'REQ-028',
    referenceNumber: 'REQ-028',
    title: 'Timing Belts - High Durability',
    value: 495000,
    approverLevel: 'L1',
    submittedAt: '2024-01-21T14:50:00Z',
    slaTargetHours: 24,
    slaElapsedHours: 14,
    status: 'pending',
    requester: 'Anjali Desai',
    dept: 'Powertrain Assembly',
    itemName: 'Timing Belts - High Durability',
    quantity: 1800,
    estimatedCost: 495000,
    budgetHead: 'Engine Components',
    budgetStatus: 'under-budget',
    urgency: 'high',
  },
  {
    id: 'APR-IND-020',
    approvalType: 'INDENT',
    referenceId: 'REQ-029',
    referenceNumber: 'REQ-029',
    title: 'Air Conditioning Compressors',
    value: 1450000,
    approverLevel: 'L2',
    submittedAt: '2024-01-19T15:45:00Z',
    slaTargetHours: 48,
    slaElapsedHours: 63,
    status: 'pending',
    requester: 'Suresh Reddy',
    dept: 'Body Shop',
    itemName: 'Air Conditioning Compressors',
    quantity: 600,
    estimatedCost: 1450000,
    budgetHead: 'Climate Control',
    budgetStatus: 'over-budget',
    urgency: 'high',
    blockerReason: 'budget',
  },
  {
    id: 'APR-IND-021',
    approvalType: 'INDENT',
    referenceId: 'REQ-030',
    referenceNumber: 'REQ-030',
    title: 'Water Pumps - Electric',
    value: 625000,
    approverLevel: 'L1',
    submittedAt: '2024-01-21T13:10:00Z',
    slaTargetHours: 24,
    slaElapsedHours: 16,
    status: 'pending',
    requester: 'Deepak Verma',
    dept: 'Powertrain Assembly',
    itemName: 'Water Pumps - Electric',
    quantity: 900,
    estimatedCost: 625000,
    budgetHead: 'Cooling Systems',
    budgetStatus: 'under-budget',
    urgency: 'high',
  },
  {
    id: 'APR-IND-022',
    approvalType: 'INDENT',
    referenceId: 'REQ-031',
    referenceNumber: 'REQ-031',
    title: 'Wheel Hubs - Integrated Bearings',
    value: 1120000,
    approverLevel: 'L2',
    submittedAt: '2024-01-20T11:25:00Z',
    slaTargetHours: 48,
    slaElapsedHours: 44,
    status: 'pending',
    requester: 'Rajesh Kumar',
    dept: 'Chassis Assembly',
    itemName: 'Wheel Hubs - Integrated Bearings',
    quantity: 1600,
    estimatedCost: 1120000,
    budgetHead: 'Wheel Systems',
    budgetStatus: 'under-budget',
    urgency: 'medium',
  },
  {
    id: 'APR-IND-023',
    approvalType: 'INDENT',
    referenceId: 'REQ-032',
    referenceNumber: 'REQ-032',
    title: 'Ignition Coils - High Energy',
    value: 385000,
    approverLevel: 'L1',
    submittedAt: '2024-01-22T02:30:00Z',
    slaTargetHours: 24,
    slaElapsedHours: 12,
    status: 'pending',
    requester: 'Priya Sharma',
    dept: 'Powertrain Assembly',
    itemName: 'Ignition Coils - High Energy',
    quantity: 2000,
    estimatedCost: 385000,
    budgetHead: 'Ignition Systems',
    budgetStatus: 'under-budget',
    urgency: 'medium',
  },
  {
    id: 'APR-IND-024',
    approvalType: 'INDENT',
    referenceId: 'REQ-033',
    referenceNumber: 'REQ-033',
    title: 'Throttle Bodies - Electronic',
    value: 845000,
    approverLevel: 'L1',
    submittedAt: '2024-01-21T10:15:00Z',
    slaTargetHours: 24,
    slaElapsedHours: 20,
    status: 'pending',
    requester: 'Vikram Mehta',
    dept: 'Powertrain Assembly',
    itemName: 'Throttle Bodies - Electronic',
    quantity: 1100,
    estimatedCost: 845000,
    budgetHead: 'Fuel Systems',
    budgetStatus: 'under-budget',
    urgency: 'high',
  },
  {
    id: 'APR-IND-025',
    approvalType: 'INDENT',
    referenceId: 'REQ-034',
    referenceNumber: 'REQ-034',
    title: 'Door Latches - Power Locking',
    value: 595000,
    approverLevel: 'L1',
    submittedAt: '2024-01-22T01:45:00Z',
    slaTargetHours: 24,
    slaElapsedHours: 13,
    status: 'pending',
    requester: 'Suresh Reddy',
    dept: 'Body Shop',
    itemName: 'Door Latches - Power Locking',
    quantity: 2200,
    estimatedCost: 595000,
    budgetHead: 'Body Components',
    budgetStatus: 'under-budget',
    urgency: 'low',
  },

  // QUOTE APPROVALS
  {
    id: 'APR-QUOTE-001',
    approvalType: 'QUOTE',
    referenceId: 'RFQ-2024-002',
    referenceNumber: 'RFQ-2024-002',
    title: 'Steel Coils RFQ - 3 Responses',
    value: 1450000,
    approverLevel: 'L2',
    submittedAt: '2024-01-20T16:45:00Z',
    slaTargetHours: 48,
    slaElapsedHours: 38,
    status: 'pending',
    requester: 'Vikram Singh',
    rfqId: 'RFQ-2024-002',
    itemName: 'Automotive Grade Steel Coils - 1.2mm',
    suppliers: [
      {
        vendorId: 'VND-002',
        vendorName: 'ArcelorMittal Automotive Steel',
        quoteAmount: 1450000,
        leadTimeDays: 12,
        onTimePct: 96,
        qualityScore: 4.7,
      },
      {
        vendorId: 'VND-009',
        vendorName: 'JSW Steel Automotive',
        quoteAmount: 1520000,
        leadTimeDays: 14,
        onTimePct: 92,
        qualityScore: 4.5,
      },
      {
        vendorId: 'VND-010',
        vendorName: 'Tata Steel Automotive',
        quoteAmount: 1580000,
        leadTimeDays: 15,
        onTimePct: 85,
        qualityScore: 4.3,
      },
    ],
    recommendedVendorId: 'VND-002',
    quoteVariancePct: 8.9,
  },
  {
    id: 'APR-QUOTE-002',
    approvalType: 'QUOTE',
    referenceId: 'RFQ-2024-003',
    referenceNumber: 'RFQ-2024-003',
    title: 'ECU Sensors RFQ - 4 Responses',
    value: 625000,
    approverLevel: 'L1',
    submittedAt: '2024-01-21T10:00:00Z',
    slaTargetHours: 24,
    slaElapsedHours: 20,
    status: 'pending',
    requester: 'Priya Sharma',
    rfqId: 'RFQ-2024-003',
    itemName: 'ECU Sensors - Bosch Oxygen Sensors',
    suppliers: [
      {
        vendorId: 'VND-003',
        vendorName: 'Bosch Automotive Solutions',
        quoteAmount: 625000,
        leadTimeDays: 8,
        onTimePct: 98,
        qualityScore: 4.8,
      },
      {
        vendorId: 'VND-011',
        vendorName: 'Continental Automotive',
        quoteAmount: 645000,
        leadTimeDays: 10,
        onTimePct: 95,
        qualityScore: 4.6,
      },
      {
        vendorId: 'VND-012',
        vendorName: 'Denso Automotive Components',
        quoteAmount: 680000,
        leadTimeDays: 12,
        onTimePct: 93,
        qualityScore: 4.5,
      },
      {
        vendorId: 'VND-013',
        vendorName: 'Delphi Technologies',
        quoteAmount: 695000,
        leadTimeDays: 14,
        onTimePct: 90,
        qualityScore: 4.4,
      },
    ],
    recommendedVendorId: 'VND-003',
    quoteVariancePct: 11.2,
  },
  {
    id: 'APR-QUOTE-003',
    approvalType: 'QUOTE',
    referenceId: 'RFQ-2024-005',
    referenceNumber: 'RFQ-2024-005',
    title: 'Battery Cells RFQ - 2 Responses',
    value: 2450000,
    approverLevel: 'Head',
    submittedAt: '2024-01-19T14:20:00Z',
    slaTargetHours: 72,
    slaElapsedHours: 70,
    status: 'pending',
    requester: 'Pradeep Nair',
    rfqId: 'RFQ-2024-005',
    itemName: 'Battery Cells - Lithium Ion 18650',
    suppliers: [
      {
        vendorId: 'VND-014',
        vendorName: 'LG Chem Automotive',
        quoteAmount: 2450000,
        leadTimeDays: 30,
        onTimePct: 97,
        qualityScore: 4.9,
      },
      {
        vendorId: 'VND-015',
        vendorName: 'Panasonic Automotive Batteries',
        quoteAmount: 2650000,
        leadTimeDays: 35,
        onTimePct: 95,
        qualityScore: 4.7,
      },
    ],
    recommendedVendorId: 'VND-014',
    quoteVariancePct: 8.2,
  },
  {
    id: 'APR-QUOTE-004',
    approvalType: 'QUOTE',
    referenceId: 'RFQ-2024-006',
    referenceNumber: 'RFQ-2024-006',
    title: 'Air Filters RFQ - 5 Responses',
    value: 385000,
    approverLevel: 'L1',
    submittedAt: '2024-01-22T08:15:00Z',
    slaTargetHours: 24,
    slaElapsedHours: 6,
    status: 'pending',
    requester: 'Rajesh Kumar',
    rfqId: 'RFQ-2024-006',
    itemName: 'Automotive Air Filters - Engine Intake HEPA',
    suppliers: [
      {
        vendorId: 'VND-019',
        vendorName: 'Mann+Hummel India',
        quoteAmount: 385000,
        leadTimeDays: 7,
        onTimePct: 94,
        qualityScore: 4.6,
      },
      {
        vendorId: 'VND-020',
        vendorName: 'Fram Automotive Filters',
        quoteAmount: 395000,
        leadTimeDays: 8,
        onTimePct: 91,
        qualityScore: 4.5,
      },
      {
        vendorId: 'VND-021',
        vendorName: 'Mahle Filter Systems',
        quoteAmount: 410000,
        leadTimeDays: 9,
        onTimePct: 93,
        qualityScore: 4.7,
      },
      {
        vendorId: 'VND-022',
        vendorName: 'Bosch Filter India',
        quoteAmount: 425000,
        leadTimeDays: 10,
        onTimePct: 96,
        qualityScore: 4.8,
      },
      {
        vendorId: 'VND-023',
        vendorName: 'Purolator Filters',
        quoteAmount: 435000,
        leadTimeDays: 12,
        onTimePct: 89,
        qualityScore: 4.4,
      },
    ],
    recommendedVendorId: 'VND-019',
    quoteVariancePct: 13.0,
  },
  {
    id: 'APR-QUOTE-005',
    approvalType: 'QUOTE',
    referenceId: 'RFQ-2024-007',
    referenceNumber: 'RFQ-2024-007',
    title: 'Clutch Components RFQ - 3 Responses',
    value: 1250000,
    approverLevel: 'L2',
    submittedAt: '2024-01-21T11:30:00Z',
    slaTargetHours: 48,
    slaElapsedHours: 34,
    status: 'pending',
    requester: 'Anjali Desai',
    rfqId: 'RFQ-2024-007',
    itemName: 'Clutch Discs & Pressure Plates',
    suppliers: [
      {
        vendorId: 'VND-024',
        vendorName: 'Valeo Clutch Systems',
        quoteAmount: 1250000,
        leadTimeDays: 18,
        onTimePct: 95,
        qualityScore: 4.7,
      },
      {
        vendorId: 'VND-025',
        vendorName: 'Luk Clutch India',
        quoteAmount: 1320000,
        leadTimeDays: 20,
        onTimePct: 92,
        qualityScore: 4.6,
      },
      {
        vendorId: 'VND-026',
        vendorName: 'Exedy Clutch Corporation',
        quoteAmount: 1380000,
        leadTimeDays: 22,
        onTimePct: 88,
        qualityScore: 4.5,
      },
    ],
    recommendedVendorId: 'VND-024',
    quoteVariancePct: 10.4,
  },
  {
    id: 'APR-QUOTE-006',
    approvalType: 'QUOTE',
    referenceId: 'RFQ-2024-008',
    referenceNumber: 'RFQ-2024-008',
    title: 'Shock Absorbers RFQ - 4 Responses',
    value: 890000,
    approverLevel: 'L1',
    submittedAt: '2024-01-22T09:45:00Z',
    slaTargetHours: 24,
    slaElapsedHours: 4,
    status: 'pending',
    requester: 'Vikram Mehta',
    rfqId: 'RFQ-2024-008',
    itemName: 'Automotive Shock Absorbers - Gas Filled Suspension',
    suppliers: [
      {
        vendorId: 'VND-027',
        vendorName: 'Bilstein India',
        quoteAmount: 890000,
        leadTimeDays: 15,
        onTimePct: 97,
        qualityScore: 4.8,
      },
      {
        vendorId: 'VND-028',
        vendorName: 'Monroe Suspension',
        quoteAmount: 925000,
        leadTimeDays: 16,
        onTimePct: 94,
        qualityScore: 4.6,
      },
      {
        vendorId: 'VND-029',
        vendorName: 'KYB Corporation',
        quoteAmount: 945000,
        leadTimeDays: 18,
        onTimePct: 91,
        qualityScore: 4.5,
      },
      {
        vendorId: 'VND-030',
        vendorName: 'Sachs Automotive',
        quoteAmount: 980000,
        leadTimeDays: 20,
        onTimePct: 89,
        qualityScore: 4.4,
      },
    ],
    recommendedVendorId: 'VND-027',
    quoteVariancePct: 10.1,
  },
  {
    id: 'APR-QUOTE-007',
    approvalType: 'QUOTE',
    referenceId: 'RFQ-2024-009',
    referenceNumber: 'RFQ-2024-009',
    title: 'Radiators RFQ - 3 Responses',
    value: 720000,
    approverLevel: 'L1',
    submittedAt: '2024-01-21T14:20:00Z',
    slaTargetHours: 24,
    slaElapsedHours: 18,
    status: 'pending',
    requester: 'Deepak Verma',
    rfqId: 'RFQ-2024-009',
    itemName: 'Automotive Radiators - Aluminum Core Engine Cooling',
    suppliers: [
      {
        vendorId: 'VND-031',
        vendorName: 'Valeo Thermal Systems',
        quoteAmount: 720000,
        leadTimeDays: 12,
        onTimePct: 96,
        qualityScore: 4.7,
      },
      {
        vendorId: 'VND-032',
        vendorName: 'Modine Manufacturing',
        quoteAmount: 745000,
        leadTimeDays: 14,
        onTimePct: 93,
        qualityScore: 4.6,
      },
      {
        vendorId: 'VND-033',
        vendorName: 'Calsonic Kansei',
        quoteAmount: 775000,
        leadTimeDays: 15,
        onTimePct: 90,
        qualityScore: 4.5,
      },
    ],
    recommendedVendorId: 'VND-031',
    quoteVariancePct: 7.6,
  },
  {
    id: 'APR-QUOTE-008',
    approvalType: 'QUOTE',
    referenceId: 'RFQ-2024-010',
    referenceNumber: 'RFQ-2024-010',
    title: 'Steering Components RFQ - 4 Responses',
    value: 1560000,
    approverLevel: 'L2',
    submittedAt: '2024-01-20T13:00:00Z',
    slaTargetHours: 48,
    slaElapsedHours: 43,
    status: 'pending',
    requester: 'Vikram Mehta',
    rfqId: 'RFQ-2024-010',
    itemName: 'Power Steering Pumps & Racks',
    suppliers: [
      {
        vendorId: 'VND-034',
        vendorName: 'TRW Automotive',
        quoteAmount: 1560000,
        leadTimeDays: 16,
        onTimePct: 94,
        qualityScore: 4.6,
      },
      {
        vendorId: 'VND-035',
        vendorName: 'JTEKT India',
        quoteAmount: 1620000,
        leadTimeDays: 18,
        onTimePct: 92,
        qualityScore: 4.5,
      },
      {
        vendorId: 'VND-036',
        vendorName: 'Nexteer Automotive',
        quoteAmount: 1680000,
        leadTimeDays: 20,
        onTimePct: 91,
        qualityScore: 4.4,
      },
      {
        vendorId: 'VND-037',
        vendorName: 'ZF Steering Systems',
        quoteAmount: 1750000,
        leadTimeDays: 22,
        onTimePct: 88,
        qualityScore: 4.3,
      },
    ],
    recommendedVendorId: 'VND-034',
    quoteVariancePct: 12.2,
  },
  {
    id: 'APR-QUOTE-009',
    approvalType: 'QUOTE',
    referenceId: 'RFQ-2024-011',
    referenceNumber: 'RFQ-2024-011',
    title: 'Window Regulators RFQ - 3 Responses',
    value: 485000,
    approverLevel: 'L1',
    submittedAt: '2024-01-22T10:30:00Z',
    slaTargetHours: 24,
    slaElapsedHours: 3,
    status: 'pending',
    requester: 'Priya Sharma',
    rfqId: 'RFQ-2024-011',
    itemName: 'Automotive Power Window Regulators & Motors',
    suppliers: [
      {
        vendorId: 'VND-038',
        vendorName: 'Magna Power Systems',
        quoteAmount: 485000,
        leadTimeDays: 10,
        onTimePct: 95,
        qualityScore: 4.6,
      },
      {
        vendorId: 'VND-039',
        vendorName: 'Brose India',
        quoteAmount: 495000,
        leadTimeDays: 11,
        onTimePct: 93,
        qualityScore: 4.5,
      },
      {
        vendorId: 'VND-040',
        vendorName: 'Johnson Controls',
        quoteAmount: 515000,
        leadTimeDays: 12,
        onTimePct: 91,
        qualityScore: 4.4,
      },
    ],
    recommendedVendorId: 'VND-038',
    quoteVariancePct: 6.2,
  },

  // PO APPROVALS
  {
    id: 'APR-PO-001',
    approvalType: 'PO',
    referenceId: 'PO-2024-002',
    referenceNumber: 'PO-2024-002',
    title: 'Steel Coils PO - ArcelorMittal',
    value: 1450000,
    approverLevel: 'L2',
    submittedAt: '2024-01-14T09:00:00Z',
    slaTargetHours: 48,
    slaElapsedHours: 192,
    status: 'pending',
    requester: 'Vikram Singh',
    poId: 'PO-2024-002',
    vendorId: 'VND-002',
    vendorName: 'ArcelorMittal Automotive Steel',
    amount: 1450000,
    costCenter: 'CC-BS-001',
    budgetCode: 'BUD-BODY-2024',
    grnStatus: 'pending',
    invoiceStatus: 'pending',
    isOffContract: false,
  },
  {
    id: 'APR-PO-002',
    approvalType: 'PO',
    referenceId: 'PO-2024-004',
    referenceNumber: 'PO-2024-004',
    title: 'Brake Pads PO - Brembo',
    value: 640000,
    approverLevel: 'L1',
    submittedAt: '2024-01-18T11:30:00Z',
    slaTargetHours: 24,
    slaElapsedHours: 96,
    status: 'pending',
    requester: 'Rajesh Kumar',
    poId: 'PO-2024-004',
    vendorId: 'VND-016',
    vendorName: 'Brembo Automotive Brakes',
    amount: 640000,
    costCenter: 'CC-BRK-001',
    budgetCode: 'BUD-BRAKE-2024',
    grnStatus: 'pending',
    invoiceStatus: 'pending',
    isOffContract: true,
  },
  {
    id: 'APR-PO-003',
    approvalType: 'PO',
    referenceId: 'PO-2024-005',
    referenceNumber: 'PO-2024-005',
    title: 'Wiring Harnesses PO - Yazaki',
    value: 425000,
    approverLevel: 'L1',
    submittedAt: '2024-01-17T15:45:00Z',
    slaTargetHours: 24,
    slaElapsedHours: 120,
    status: 'pending',
    requester: 'Suresh Reddy',
    poId: 'PO-2024-005',
    vendorId: 'VND-017',
    vendorName: 'Yazaki Wiring Systems',
    amount: 425000,
    costCenter: 'CC-ELEC-001',
    budgetCode: 'BUD-WIRING-2024',
    grnStatus: 'pending',
    invoiceStatus: 'pending',
    isOffContract: false,
  },
  {
    id: 'APR-PO-004',
    approvalType: 'PO',
    referenceId: 'PO-2024-008',
    referenceNumber: 'PO-2024-008',
    title: 'Transmission Gears PO - Aisin',
    value: 1125000,
    approverLevel: 'L2',
    submittedAt: '2024-01-15T10:20:00Z',
    slaTargetHours: 48,
    slaElapsedHours: 168,
    status: 'pending',
    requester: 'Anjali Desai',
    poId: 'PO-2024-008',
    vendorId: 'VND-018',
    vendorName: 'Aisin Seiki Transmission',
    amount: 1125000,
    costCenter: 'CC-PT-001',
    budgetCode: 'BUD-TRANS-2024',
    grnStatus: 'pending',
    invoiceStatus: 'pending',
    isOffContract: false,
  },
  {
    id: 'APR-PO-005',
    approvalType: 'PO',
    referenceId: 'PO-2024-012',
    referenceNumber: 'PO-2024-012',
    title: 'Paint & Coatings PO - PPG',
    value: 875000,
    approverLevel: 'L1',
    submittedAt: '2024-01-21T13:15:00Z',
    slaTargetHours: 24,
    slaElapsedHours: 11,
    status: 'pending',
    requester: 'Priya Sharma',
    poId: 'PO-2024-012',
    vendorId: 'VND-007',
    vendorName: 'PPG Automotive Coatings',
    amount: 875000,
    costCenter: 'CC-PAINT-001',
    budgetCode: 'BUD-PAINT-2024',
    grnStatus: 'pending',
    invoiceStatus: 'pending',
    isOffContract: false,
  },
  {
    id: 'APR-PO-006',
    approvalType: 'PO',
    referenceId: 'PO-2024-015',
    referenceNumber: 'PO-2024-015',
    title: 'Engine Bearings PO - SKF',
    value: 875000,
    approverLevel: 'L1',
    submittedAt: '2024-01-22T08:00:00Z',
    slaTargetHours: 24,
    slaElapsedHours: 5,
    status: 'pending',
    requester: 'Priya Sharma',
    poId: 'PO-2024-015',
    vendorId: 'VND-001',
    vendorName: 'SKF Automotive Bearings',
    amount: 875000,
    costCenter: 'CC-PT-002',
    budgetCode: 'BUD-POWERTRAIN-2024',
    grnStatus: 'pending',
    invoiceStatus: 'pending',
    isOffContract: false,
  },
  {
    id: 'APR-PO-007',
    approvalType: 'PO',
    referenceId: 'PO-2024-016',
    referenceNumber: 'PO-2024-016',
    title: 'ECU Sensors PO - Bosch',
    value: 625000,
    approverLevel: 'L1',
    submittedAt: '2024-01-21T09:30:00Z',
    slaTargetHours: 24,
    slaElapsedHours: 21,
    status: 'pending',
    requester: 'Deepak Verma',
    poId: 'PO-2024-016',
    vendorId: 'VND-003',
    vendorName: 'Bosch Automotive Solutions',
    amount: 625000,
    costCenter: 'CC-ELEC-002',
    budgetCode: 'BUD-ELECTRONICS-2024',
    grnStatus: 'pending',
    invoiceStatus: 'pending',
    isOffContract: false,
  },
  {
    id: 'APR-PO-008',
    approvalType: 'PO',
    referenceId: 'PO-2024-018',
    referenceNumber: 'PO-2024-018',
    title: 'Tires PO - Michelin',
    value: 3200000,
    approverLevel: 'Head',
    submittedAt: '2024-01-19T10:15:00Z',
    slaTargetHours: 72,
    slaElapsedHours: 69,
    status: 'pending',
    requester: 'Amit Patel',
    poId: 'PO-2024-018',
    vendorId: 'VND-004',
    vendorName: 'Michelin Tire Manufacturing',
    amount: 3200000,
    costCenter: 'CC-CHASSIS-001',
    budgetCode: 'BUD-TIRES-2024',
    grnStatus: 'pending',
    invoiceStatus: 'pending',
    isOffContract: false,
  },
  {
    id: 'APR-PO-009',
    approvalType: 'PO',
    referenceId: 'PO-2024-020',
    referenceNumber: 'PO-2024-020',
    title: 'Headlights PO - Osram',
    value: 1250000,
    approverLevel: 'L2',
    submittedAt: '2024-01-20T14:45:00Z',
    slaTargetHours: 48,
    slaElapsedHours: 40,
    status: 'pending',
    requester: 'Suresh Reddy',
    poId: 'PO-2024-020',
    vendorId: 'VND-041',
    vendorName: 'Osram Automotive Lighting',
    amount: 1250000,
    costCenter: 'CC-ELEC-003',
    budgetCode: 'BUD-LIGHTING-2024',
    grnStatus: 'pending',
    invoiceStatus: 'pending',
    isOffContract: true,
  },
  {
    id: 'APR-PO-010',
    approvalType: 'PO',
    referenceId: 'PO-2024-021',
    referenceNumber: 'PO-2024-021',
    title: 'Seat Covers PO - Lear',
    value: 580000,
    approverLevel: 'L1',
    submittedAt: '2024-01-22T07:30:00Z',
    slaTargetHours: 24,
    slaElapsedHours: 6,
    status: 'pending',
    requester: 'Rajesh Kumar',
    poId: 'PO-2024-021',
    vendorId: 'VND-042',
    vendorName: 'Lear Corporation India',
    amount: 580000,
    costCenter: 'CC-INTERIOR-001',
    budgetCode: 'BUD-INTERIOR-2024',
    grnStatus: 'pending',
    invoiceStatus: 'pending',
    isOffContract: false,
  },
  {
    id: 'APR-PO-011',
    approvalType: 'PO',
    referenceId: 'PO-2024-022',
    referenceNumber: 'PO-2024-022',
    title: 'Fuel Pumps PO - Continental',
    value: 695000,
    approverLevel: 'L1',
    submittedAt: '2024-01-21T12:20:00Z',
    slaTargetHours: 24,
    slaElapsedHours: 18,
    status: 'pending',
    requester: 'Anjali Desai',
    poId: 'PO-2024-022',
    vendorId: 'VND-005',
    vendorName: 'Continental Automotive',
    amount: 695000,
    costCenter: 'CC-PT-003',
    budgetCode: 'BUD-FUEL-SYS-2024',
    grnStatus: 'pending',
    invoiceStatus: 'pending',
    isOffContract: false,
  },
  {
    id: 'APR-PO-012',
    approvalType: 'PO',
    referenceId: 'PO-2024-024',
    referenceNumber: 'PO-2024-024',
    title: 'Coolant Hoses PO - Gates',
    value: 325000,
    approverLevel: 'L1',
    submittedAt: '2024-01-22T11:15:00Z',
    slaTargetHours: 24,
    slaElapsedHours: 2,
    status: 'pending',
    requester: 'Deepak Verma',
    poId: 'PO-2024-024',
    vendorId: 'VND-043',
    vendorName: 'Gates India',
    amount: 325000,
    costCenter: 'CC-PT-004',
    budgetCode: 'BUD-COOLING-2024',
    grnStatus: 'pending',
    invoiceStatus: 'pending',
    isOffContract: true,
  },
  {
    id: 'APR-PO-013',
    approvalType: 'PO',
    referenceId: 'PO-2024-025',
    referenceNumber: 'PO-2024-025',
    title: 'Spark Plugs PO - NGK',
    value: 245000,
    approverLevel: 'L1',
    submittedAt: '2024-01-21T16:30:00Z',
    slaTargetHours: 24,
    slaElapsedHours: 14,
    status: 'pending',
    requester: 'Vikram Mehta',
    poId: 'PO-2024-025',
    vendorId: 'VND-044',
    vendorName: 'NGK Spark Plugs India',
    amount: 245000,
    costCenter: 'CC-PT-005',
    budgetCode: 'BUD-IGNITION-2024',
    grnStatus: 'pending',
    invoiceStatus: 'pending',
    isOffContract: false,
  },
  {
    id: 'APR-PO-014',
    approvalType: 'PO',
    referenceId: 'PO-2024-027',
    referenceNumber: 'PO-2024-027',
    title: 'Exhaust Systems PO - Faurecia',
    value: 1850000,
    approverLevel: 'L2',
    submittedAt: '2024-01-19T09:45:00Z',
    slaTargetHours: 48,
    slaElapsedHours: 73,
    status: 'pending',
    requester: 'Amit Patel',
    poId: 'PO-2024-027',
    vendorId: 'VND-045',
    vendorName: 'Faurecia Emissions Control',
    amount: 1850000,
    costCenter: 'CC-PT-006',
    budgetCode: 'BUD-EXHAUST-2024',
    grnStatus: 'pending',
    invoiceStatus: 'pending',
    isOffContract: false,
  },
  {
    id: 'APR-PO-015',
    approvalType: 'PO',
    referenceId: 'PO-2024-028',
    referenceNumber: 'PO-2024-028',
    title: 'Windshield Wipers PO - Valeo',
    value: 185000,
    approverLevel: 'L1',
    submittedAt: '2024-01-22T06:00:00Z',
    slaTargetHours: 24,
    slaElapsedHours: 8,
    status: 'pending',
    requester: 'Priya Sharma',
    poId: 'PO-2024-028',
    vendorId: 'VND-046',
    vendorName: 'Valeo Wiper Systems',
    amount: 185000,
    costCenter: 'CC-BS-002',
    budgetCode: 'BUD-WIPERS-2024',
    grnStatus: 'pending',
    invoiceStatus: 'pending',
    isOffContract: false,
  },
  {
    id: 'APR-PO-016',
    approvalType: 'PO',
    referenceId: 'PO-2024-030',
    referenceNumber: 'PO-2024-030',
    title: 'Horn Systems PO - Hella',
    value: 145000,
    approverLevel: 'L1',
    submittedAt: '2024-01-22T05:30:00Z',
    slaTargetHours: 24,
    slaElapsedHours: 9,
    status: 'pending',
    requester: 'Suresh Reddy',
    poId: 'PO-2024-030',
    vendorId: 'VND-047',
    vendorName: 'Hella India',
    amount: 145000,
    costCenter: 'CC-ELEC-004',
    budgetCode: 'BUD-HORNS-2024',
    grnStatus: 'pending',
    invoiceStatus: 'pending',
    isOffContract: false,
  },
  {
    id: 'APR-PO-017',
    approvalType: 'PO',
    referenceId: 'PO-2024-031',
    referenceNumber: 'PO-2024-031',
    title: 'Door Handles PO - U-Shin',
    value: 420000,
    approverLevel: 'L1',
    submittedAt: '2024-01-21T08:20:00Z',
    slaTargetHours: 24,
    slaElapsedHours: 28,
    status: 'pending',
    requester: 'Rajesh Kumar',
    poId: 'PO-2024-031',
    vendorId: 'VND-048',
    vendorName: 'U-Shin India',
    amount: 420000,
    costCenter: 'CC-BS-003',
    budgetCode: 'BUD-HANDLES-2024',
    grnStatus: 'received',
    invoiceStatus: 'pending',
    isOffContract: true,
  },
  {
    id: 'APR-PO-018',
    approvalType: 'PO',
    referenceId: 'PO-2024-033',
    referenceNumber: 'PO-2024-033',
    title: 'Alternators PO - Denso',
    value: 980000,
    approverLevel: 'L2',
    submittedAt: '2024-01-20T15:00:00Z',
    slaTargetHours: 48,
    slaElapsedHours: 39,
    status: 'pending',
    requester: 'Anjali Desai',
    poId: 'PO-2024-033',
    vendorId: 'VND-008',
    vendorName: 'Denso Automotive Components',
    amount: 980000,
    costCenter: 'CC-ELEC-005',
    budgetCode: 'BUD-CHARGING-2024',
    grnStatus: 'pending',
    invoiceStatus: 'pending',
    isOffContract: false,
  },
  {
    id: 'APR-PO-019',
    approvalType: 'PO',
    referenceId: 'PO-2024-035',
    referenceNumber: 'PO-2024-035',
    title: 'Brake Calipers PO - Akebono',
    value: 1150000,
    approverLevel: 'L2',
    submittedAt: '2024-01-19T11:30:00Z',
    slaTargetHours: 48,
    slaElapsedHours: 71,
    status: 'pending',
    requester: 'Vikram Mehta',
    poId: 'PO-2024-035',
    vendorId: 'VND-049',
    vendorName: 'Akebono Brake Corporation',
    amount: 1150000,
    costCenter: 'CC-BRK-002',
    budgetCode: 'BUD-CALIPERS-2024',
    grnStatus: 'pending',
    invoiceStatus: 'pending',
    isOffContract: false,
  },
  {
    id: 'APR-PO-020',
    approvalType: 'PO',
    referenceId: 'PO-2024-036',
    referenceNumber: 'PO-2024-036',
    title: 'Mirrors PO - SMR',
    value: 385000,
    approverLevel: 'L1',
    submittedAt: '2024-01-22T04:15:00Z',
    slaTargetHours: 24,
    slaElapsedHours: 10,
    status: 'pending',
    requester: 'Priya Sharma',
    poId: 'PO-2024-036',
    vendorId: 'VND-050',
    vendorName: 'SMR Automotive Mirrors',
    amount: 385000,
    costCenter: 'CC-BS-004',
    budgetCode: 'BUD-MIRRORS-2024',
    grnStatus: 'pending',
    invoiceStatus: 'pending',
    isOffContract: false,
  },
];

export const mockActivityFeed: ActivityFeedItem[] = [
  {
    id: 'ACT-001',
    title: 'Production Line Alert: Engine Bearings Stock Critical',
    description: 'Stock level below safety threshold. Immediate procurement required to avoid production halt.',
    timestamp: '2024-01-22T10:30:00Z',
    priority: 'critical',
    actionLabel: 'View Request REQ-001',
  },
  {
    id: 'ACT-002',
    title: 'Quality Alert: Steel Coils Inspection Pending',
    description: 'Batch QC-240122 requires inspection before approval. 120 coils awaiting clearance.',
    timestamp: '2024-01-22T09:15:00Z',
    priority: 'high',
    actionLabel: 'Review Quality Report',
  },
  {
    id: 'ACT-003',
    title: 'Vendor Performance: Bosch - 98% On-Time Delivery',
    description: 'Excellent performance this month. Consider expanding contract scope.',
    timestamp: '2024-01-22T08:45:00Z',
    priority: 'medium',
  },
  {
    id: 'ACT-004',
    title: 'RFQ Deadline Approaching: RFQ-2024-002',
    description: 'Steel Coils RFQ closing in 6 days. 3 suppliers responded, 1 pending.',
    timestamp: '2024-01-22T07:30:00Z',
    priority: 'high',
    actionLabel: 'Review Quotes',
  },
  {
    id: 'ACT-005',
    title: 'Contract Renewal: SKF Bearings Contract Expires in 334 Days',
    description: 'Annual contract renewal window opens in 30 days. Begin negotiations.',
    timestamp: '2024-01-21T16:20:00Z',
    priority: 'low',
    actionLabel: 'Schedule Meeting',
  },
];

export const mockActionQueue: ActionQueueItem[] = [
  {
    id: 'AQ-001',
    type: 'validation',
    title: 'Validate REQ-001: Engine Bearings - Critical',
    description: 'Production line component. Validation required immediately to prevent downtime.',
    priority: 'critical',
    dueDate: 'Today',
    entityType: 'Request',
  },
  {
    id: 'AQ-002',
    type: 'approval',
    title: 'Approve PO-2024-002: ₹1,450,000',
    description: 'Steel Coils purchase order pending approval for 8 days. Production dependency.',
    priority: 'critical',
    dueDate: 'Today',
    entityType: 'Purchase Order',
  },
  {
    id: 'AQ-003',
    type: 'rfq-reminder',
    title: 'Send RFQ reminder: RFQ-2024-002',
    description: '1 supplier has not responded. Deadline in 6 days. Critical for production.',
    priority: 'high',
    dueDate: 'Today',
    entityType: 'RFQ',
  },
  {
    id: 'AQ-004',
    type: 'contract-renewal',
    title: 'Review contract renewal: CNT-001',
    description: 'SKF Bearings Annual Supply Contract. Renewal window opens in 30 days.',
    priority: 'low',
    dueDate: 'Next week',
    entityType: 'Contract',
  },
  {
    id: 'AQ-005',
    type: 'validation',
    title: 'Validate REQ-010: Suspension Coil Springs',
    description: 'Critical chassis component. Fast-track validation required.',
    priority: 'high',
    dueDate: 'Today',
    entityType: 'Request',
  },
  {
    id: 'AQ-006',
    type: 'approval',
    title: 'Approve PO-2024-008: ₹1,125,000',
    description: 'Transmission Gears purchase order pending approval for 7 days.',
    priority: 'high',
    dueDate: 'Today',
    entityType: 'Purchase Order',
  },
  {
    id: 'AQ-007',
    type: 'rfq-reminder',
    title: 'Send RFQ reminder: RFQ-2024-005',
    description: '1 supplier has not responded. Battery cells RFQ deadline in 10 days.',
    priority: 'medium',
    dueDate: 'Tomorrow',
    entityType: 'RFQ',
  },
];
